<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example.mosaic</groupId>
    <artifactId>mosaic-apps</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <mosaic.dir>D:/mosaic</mosaic.dir>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-application</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-application-25.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-objects</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-objects-25.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-interactions</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-interactions-25.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-utils</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-utils-25.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-geomath</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-geomath-25.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-rti-api</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-rti-api-25.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mosaic</groupId>
            <artifactId>mosaic-routing</artifactId>
            <version>25.2</version>
            <scope>system</scope>
            <systemPath>${mosaic.dir}/lib/mosaic-routing-25.2.jar</systemPath>
        </dependency>
    </dependencies>
</project>
